// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: learnstarport/xmr_tx.proto

package types

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type XmrTx struct {
	Creator string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Id      uint64 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Txid    string `protobuf:"bytes,3,opt,name=txid,proto3" json:"txid,omitempty"`
	To      string `protobuf:"bytes,4,opt,name=to,proto3" json:"to,omitempty"`
	From    string `protobuf:"bytes,5,opt,name=from,proto3" json:"from,omitempty"`
	Amount  string `protobuf:"bytes,6,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (m *XmrTx) Reset()         { *m = XmrTx{} }
func (m *XmrTx) String() string { return proto.CompactTextString(m) }
func (*XmrTx) ProtoMessage()    {}
func (*XmrTx) Descriptor() ([]byte, []int) {
	return fileDescriptor_734faf37a7f0e9c1, []int{0}
}
func (m *XmrTx) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *XmrTx) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_XmrTx.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *XmrTx) XXX_Merge(src proto.Message) {
	xxx_messageInfo_XmrTx.Merge(m, src)
}
func (m *XmrTx) XXX_Size() int {
	return m.Size()
}
func (m *XmrTx) XXX_DiscardUnknown() {
	xxx_messageInfo_XmrTx.DiscardUnknown(m)
}

var xxx_messageInfo_XmrTx proto.InternalMessageInfo

func (m *XmrTx) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *XmrTx) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *XmrTx) GetTxid() string {
	if m != nil {
		return m.Txid
	}
	return ""
}

func (m *XmrTx) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *XmrTx) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *XmrTx) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func init() {
	proto.RegisterType((*XmrTx)(nil), "turtlebasket.learnstarport.learnstarport.XmrTx")
}

func init() { proto.RegisterFile("learnstarport/xmr_tx.proto", fileDescriptor_734faf37a7f0e9c1) }

var fileDescriptor_734faf37a7f0e9c1 = []byte{
	// 243 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0xb1, 0x4e, 0xc3, 0x30,
	0x18, 0x84, 0xe3, 0x90, 0x06, 0xe1, 0x81, 0xc1, 0x42, 0xc8, 0xea, 0x60, 0x55, 0x4c, 0x59, 0x88,
	0x07, 0x56, 0x26, 0x1e, 0xa1, 0x42, 0x08, 0xb1, 0x20, 0xa7, 0x31, 0x21, 0xa2, 0xee, 0x1f, 0xfd,
	0xf9, 0x23, 0x99, 0x91, 0x37, 0xe0, 0xb1, 0x18, 0x3b, 0x32, 0xa2, 0xe4, 0x45, 0x90, 0x5d, 0x10,
	0x64, 0xbb, 0x3b, 0x7d, 0x37, 0xdc, 0xf1, 0xe5, 0xd6, 0x1a, 0xdc, 0xf5, 0x64, 0xb0, 0x03, 0x24,
	0xed, 0x1d, 0x3e, 0x92, 0x2f, 0x3b, 0x04, 0x02, 0x51, 0xd0, 0x80, 0xb4, 0xb5, 0x95, 0xe9, 0x5f,
	0x2c, 0x95, 0x33, 0x70, 0xee, 0x96, 0x67, 0x0d, 0x34, 0x10, 0x4b, 0x3a, 0xa8, 0x43, 0xff, 0xe2,
	0x8d, 0xf1, 0xc5, 0xbd, 0xc3, 0x5b, 0x2f, 0x24, 0x3f, 0xde, 0xa0, 0x35, 0x04, 0x28, 0xd9, 0x8a,
	0x15, 0x27, 0xeb, 0x5f, 0x2b, 0x4e, 0x79, 0xda, 0xd6, 0x32, 0x5d, 0xb1, 0x22, 0x5b, 0xa7, 0x6d,
	0x2d, 0x04, 0xcf, 0xc8, 0xb7, 0xb5, 0x3c, 0x8a, 0x58, 0xd4, 0x81, 0x21, 0x90, 0x59, 0x4c, 0x52,
	0x82, 0xc0, 0x3c, 0x21, 0x38, 0xb9, 0x38, 0x30, 0x41, 0x8b, 0x73, 0x9e, 0x1b, 0x07, 0xc3, 0x8e,
	0x64, 0x1e, 0xd3, 0x1f, 0x77, 0x73, 0xf7, 0x31, 0x2a, 0xb6, 0x1f, 0x15, 0xfb, 0x1a, 0x15, 0x7b,
	0x9f, 0x54, 0xb2, 0x9f, 0x54, 0xf2, 0x39, 0xa9, 0xe4, 0xe1, 0xba, 0x69, 0xe9, 0x79, 0xa8, 0xca,
	0x0d, 0x38, 0xfd, 0x7f, 0xa8, 0x8e, 0xd3, 0x2e, 0xff, 0x2e, 0xd1, 0xf3, 0x8b, 0xe8, 0xb5, 0xb3,
	0x7d, 0x95, 0xc7, 0x89, 0x57, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xd8, 0xe2, 0x72, 0x81, 0x40,
	0x01, 0x00, 0x00,
}

func (m *XmrTx) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *XmrTx) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *XmrTx) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Amount) > 0 {
		i -= len(m.Amount)
		copy(dAtA[i:], m.Amount)
		i = encodeVarintXmrTx(dAtA, i, uint64(len(m.Amount)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.From) > 0 {
		i -= len(m.From)
		copy(dAtA[i:], m.From)
		i = encodeVarintXmrTx(dAtA, i, uint64(len(m.From)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.To) > 0 {
		i -= len(m.To)
		copy(dAtA[i:], m.To)
		i = encodeVarintXmrTx(dAtA, i, uint64(len(m.To)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Txid) > 0 {
		i -= len(m.Txid)
		copy(dAtA[i:], m.Txid)
		i = encodeVarintXmrTx(dAtA, i, uint64(len(m.Txid)))
		i--
		dAtA[i] = 0x1a
	}
	if m.Id != 0 {
		i = encodeVarintXmrTx(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintXmrTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintXmrTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovXmrTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *XmrTx) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovXmrTx(uint64(l))
	}
	if m.Id != 0 {
		n += 1 + sovXmrTx(uint64(m.Id))
	}
	l = len(m.Txid)
	if l > 0 {
		n += 1 + l + sovXmrTx(uint64(l))
	}
	l = len(m.To)
	if l > 0 {
		n += 1 + l + sovXmrTx(uint64(l))
	}
	l = len(m.From)
	if l > 0 {
		n += 1 + l + sovXmrTx(uint64(l))
	}
	l = len(m.Amount)
	if l > 0 {
		n += 1 + l + sovXmrTx(uint64(l))
	}
	return n
}

func sovXmrTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozXmrTx(x uint64) (n int) {
	return sovXmrTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *XmrTx) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowXmrTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: XmrTx: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: XmrTx: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowXmrTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthXmrTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthXmrTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowXmrTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Txid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowXmrTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthXmrTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthXmrTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Txid = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field To", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowXmrTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthXmrTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthXmrTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.To = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field From", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowXmrTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthXmrTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthXmrTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.From = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowXmrTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthXmrTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthXmrTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Amount = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipXmrTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthXmrTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipXmrTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowXmrTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowXmrTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowXmrTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthXmrTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupXmrTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthXmrTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthXmrTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowXmrTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupXmrTx = fmt.Errorf("proto: unexpected end of group")
)
